#修改server端口
server:
    port: 5050
    # context-path: /helloboot
spring:
    application:
      name: healthdemo

#eureka:
    #client:
      #serviceUrl:
      #defaultZone: http://localhost:8000/eureka

#数据源
#spring:
#datasource:
     # url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=false
     # username: root
     # password: root